### ISSUE TITLE
Support K2 Compiler

### ISSUE THREAD

**Issue by ZacSweers** [Kotlin/binary-compatibility-validator#139]
As of `0.13.1`, API validation will fail with the below exception when running on K2-compiled code.

```
Caused by: java.lang.IllegalStateException: Incompatible version of Kotlin metadata.
Maximal supported Kotlin metadata version: 1.8.0,
dev/zacsweers/redacted/compiler/RedactedCommandLineProcessor Kotlin metadata version: 2.0.0.
As a workaround, it is possible to manually update 'kotlinx-metadata-jvm' version in your project.
        at kotlinx.validation.api.KotlinMetadataVisibilitiesKt.getKotlinMetadata(KotlinMetadataVisibilities.kt:72)
        at kotlinx.validation.api.KotlinMetadataVisibilitiesKt.toClassVisibility(KotlinMetadataVisibilities.kt:153)
        at kotlinx.validation.api.KotlinMetadataVisibilitiesKt.readKotlinVisibilities(KotlinMetadataVisibilities.kt:165)
        at kotlinx.validation.api.KotlinSignaturesLoadingKt.loadApiFromJvmClasses(KotlinSignaturesLoading.kt:35)
        at kotlinx.validation.api.KotlinSignaturesLoadingKt.loadApiFromJvmClasses$default(KotlinSignaturesLoading.kt:22)
```

For now, I'm working around it by dynamically disabling validation when K2 is enabled (snippet using Kotlin 1.9.0-Beta)

```kotlin
apiValidation {
  validationDisabled = findProperty("kotlin.experimental.tryK2") == "true"
}
```

Filing so I have something to link above that disabling for posterity :)

**Comment by qwwdfsad** [comment]
Was fixed in 0.13.2
