### ISSUE TITLE
Can't apply the BCV plugin to the multimode projects having the KMP applied only in sub-module

### ISSUE THREAD

**Issue by fzhinkin** [Kotlin/binary-compatibility-validator#190]
For a project having following structure:

```
root project: apply BCV plugin
  sub-project: apply kotlin-multiplatform plugin
```

tasks fails with:
```
* Exception is:
java.lang.NoClassDefFoundError: org/jetbrains/kotlin/gradle/dsl/KotlinMultiplatformExtension
        at kotlinx.validation.BinaryCompatibilityValidatorPlugin$configureMultiplatformPlugin$1.execute(BinaryCompatibilityValidatorPlugin.kt:57)
        at kotlinx.validation.BinaryCompatibilityValidatorPlugin$configureMultiplatformPlugin$1.execute(BinaryCompatibilityValidatorPlugin.kt:16)
        at kotlinx.validation.BinaryCompatibilityValidatorPlugin$configurePlugin$1.execute(BinaryCompatibilityValidatorPlugin.kt:49)
        at kotlinx.validation.BinaryCompatibilityValidatorPlugin$configurePlugin$1.execute(BinaryCompatibilityValidatorPlugin.kt:16)
```

There's no such an issue for Kotlin/JVM plugin applied to a sub-project.

**Comment by fzhinkin** [comment]
Reproducer: https://github.com/fzhinkin/bcv-190-repro

**Comment by shanshin** [comment]
As part of [the migration of separate BCV functionality to Kotlin Gradle Plugin](https://youtrack.jetbrains.com/issue/KT-71098/Migrate-Binary-Compatibility-Validator-to-Kotlin-Gradle-Plugin), the addition of new features to a separate plugin has been discontinued.

This issue is not relevant for the code running inside KGP.
