### ISSUE TITLE
Daemon compilation failed: null when building Ktor API dump

### ISSUE THREAD

**Issue by e5l** [Kotlin/binary-compatibility-validator#272]
After updating Kotlin to the 2.0.21, we started facing frequent API check task failure for Ktor:

https://ktor.teamcity.com/buildConfiguration/Ktor_KtorMatrixCoreAPICheck/288142?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandPull+Request+Details=true&expandBuildProblemsSection=true&expandBuildChangesSection=true&showLog=288142_17864_491.17863&logFilter=debug&logView=flowAware

```
    e: Daemon compilation failed: null
09:40:36     java.lang.Exception
09:40:36       at org.jetbrains.kotlin.daemon.common.CompileService$CallResult$Error.get(CompileService.kt:69)
09:40:36       at org.jetbrains.kotlin.daemon.common.CompileService$CallResult$Error.get(CompileService.kt:65)
09:40:36       at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.compileWithDaemon(GradleKotlinCompilerWork.kt:240)
09:40:36       at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.compileWithDaemonOrFallbackImpl(GradleKotlinCompilerWork.kt:159)
09:40:36       at org.jetbrains.kotlin.compilerRunner.GradleKotlinCompilerWork.run(GradleKotlinCompilerWork.kt:111)
09:40:36       at org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction.execute(GradleCompilerRunnerWithWorkers.kt:76)
09:40:37       at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
09:40:37       at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
09:40:37       at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
09:40:37       at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
09:40:37       at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
09:40:37       at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
09:40:37       at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
09:40:37       at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
09:40:37       at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
09:40:37       at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
09:40:37       at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
09:40:37       at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
09:40:37       at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
09:40:37       at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
09:40:37       at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
09:40:37       at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
09:40:37       at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$0(DefaultWorkerExecutor.java:174)
09:40:37       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
09:40:37       at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:194)
09:40:37       at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.access$700(DefaultConditionalExecutionQueue.java:127)
09:40:37       at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:169)
09:40:37       at org.gradle.internal.Factories$1.create(Factories.java:31)
09:40:37       at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:263)
09:40:37       at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:127)
09:40:37       at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:132)
09:40:37       at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
09:40:37       at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:133)
09:40:37       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
09:40:37       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
09:40:37       at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
09:40:37       at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
09:40:37       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
09:40:37       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
09:40:37       at java.base/java.lang.Thread.run(Thread.java:1583)
09:40:37     Caused by: java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is:
09:40:37       java.net.SocketTimeoutException: Read timed out
09:40:37       at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:308)
09:40:37       at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204)
09:40:37       at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:134)
09:40:37       at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:215)
09:40:37       at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:160)
09:40:37       at jdk.proxy1/jdk.proxy1.$Proxy2.add(Unknown Source)
09:40:37       at org.jetbrains.kotlin.daemon.report.CompileIterationICReporter.reportCompileIteration(CompileIterationICReporter.kt:21)
09:40:37       at org.jetbrains.kotlin.daemon.report.CompositeICReporter.reportCompileIteration(CompositeICReporter.kt:19)
09:40:37       at org.jetbrains.kotlin.build.report.BuildReporter.reportCompileIteration(BuildReporter.kt)
09:40:37       at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:534)
09:40:37       at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:423)
09:40:37       at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:301)
09:40:37       at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:129)
09:40:37       at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile$default(IncrementalCompilerRunner.kt:113)
09:40:37       at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execJsIncrementalCompiler(CompileServiceImpl.kt:609)
09:40:37       at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execJsIncrementalCompiler(CompileServiceImpl.kt:92)
09:40:37       at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1758)
09:40:37       at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
09:40:37       at java.base/java.lang.reflect.Method.invoke(Method.java:580)
09:40:37       at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
09:40:37       at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
09:40:37       at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
09:40:37       at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
09:40:37       at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
09:40:37       at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
09:40:37       at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
09:40:37       at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
09:40:37       at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
09:40:37       at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
09:40:37       ... 3 more
09:40:37     Caused by: java.net.SocketTimeoutException: Read timed out
09:40:37       at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:278)
09:40:37       at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304)
09:40:37       at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
09:40:37       at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
09:40:37       at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
09:40:37       at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:291)
09:40:37       at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:325)
09:40:37       at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:312)
09:40:37       at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295)
09:40:37       at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275)
09:40:37       at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:247)
09:40:37       ... 31 more
```

**Comment by fzhinkin** [comment]
@e5l I don't think the issue has something to do with BCV. Similar failures could be found among "JS on Chrome" tasks too: https://ktor.teamcity.com/buildConfiguration/Ktor_KtorMatrixJavaScriptChromeNodeJs/287626?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandPull+Request+Details=true&expandBuildProblemsSection=true&expandBuildChangesSection=true&logFilter=debug&logView=flowAware

**Comment by e5l** [comment]
yep, the problem looks like it is deeper
